variable "prefix" {}
variable "project" {}
variable "application" {}
variable "region" {}
variable "cidr_block" {}
variable "azs" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "k8s_version" {}
variable "desired_capacity" {}
variable "small_instance_desired_capacity" {}
variable "large_instance_desired_capacity" {}
variable "small_instance_types" {}
variable "large_instance_types" {}
variable "max_size" {}
variable "min_size" {}
variable "eks_cw_logging" {}
variable "max_unavailable" {}
variable "aws_iam" {}
variable "endpoint_private_access" {}
variable "endpoint_public_access" {}
variable "public_eks_tag" {}
variable "private_eks_tag" {}
variable "create_vpc" {}
variable "eks_cluster_name" {}
variable "cluster_name" {}
variable "account_id" {}
variable "enable_nat_gateway" {}
